GRID_SIZE = 40
NUM_CELLS = 10
SIZE = NUM_CELLS * GRID_SIZE
DEBUG = True
OUTSIDE_GRID = (-1, -1)
MISS = 2
HIT = 3
EMPTY = 0
SHIP = 1

#Offset of players
OFFSET_PLAYER_ONE = 2.5
OFFSET_PLAYER_TWO = 0.1

#video settings
SCREEN_SIZE = (1280, 720)
FPS_LIMIT = 60